### PR TITLE
Merge 2d halo adjoint exchange code from JCSDA-internal MPAS-Model repo to public MPAS-Model repo

### PR DESCRIPTION
**Pull request by jim-p-w**
This is a preliminary PR, as the new unit tests for the adjoint halo exchange is failing.

### CODE REVIEW

**Comment by jim-p-w** [comment]
@mgduda @byoung-joo Can you look at the **findInteriorCells** routine in the test code? I think I am misidentifying some edge cells as interior cells.
When I run the test for the adjoint halo exchange, it is failing because some cells I think are interior cells are getting updated during the adjoint halo exchange, which should not happen.

**Comment by byoung-joo** [comment]
To me, the findInteriorCells routine looks good. It identifies the own cells that do not adjoin the halo cells.

Let me build and try running your test code on Derecho, following your instruction, @jim-p-w !

**Comment by byoung-joo** [comment]
I feel something is wrong in the adjoint code, as Jim mentioned.  Let me take a look further. I might be back with more question on the details of original halo exchange code.   This unit test really helps!

**Comment by byoung-joo** [comment]
@mgduda ,

I wonder what the usual value is for `nHaloLayers` in a real case. 

In this unit test, I see `nHaloLayers = 3` and in my original work, I assumed that `nHaloLayers` would be 1.

**Comment by byoung-joo** [comment]
I see 

* for core_test, it is defined as 3
https://github.com/jim-p-w/MPAS-Model/blob/master/src/core_test/Registry.xml#L23

* for core_atmosphere, it is defined as 2
https://github.com/jim-p-w/MPAS-Model/blob/master/src/core_atmosphere/Registry.xml#L245-L248

Finally, I realized that the adjointness check might pass depending on _how the test is written_ or _how the test values are set_, even if `nHaloLayers = 2` in a real case.  Let me think about this further.

**Comment by byoung-joo** [comment]
> In this unit test, I see nHaloLayers = 3 and in my original work, I assumed that nHaloLayers would be 1.

@jim-p-w , this is why we see the value changes for _**interior cells**_ .  Let me get back to you early next week with what can be a good unit test for adjoint operator.

**Comment by jim-p-w** [comment]
> > In this unit test, I see nHaloLayers = 3 and in my original work, I assumed that nHaloLayers would be 1.
> 
> @jim-p-w , this is why we see the value changes for _**interior cells**_ . Let me get back to you early next week with what can be a good unit test for adjoint operator.

@byoung-joo I see that all of the updates to the interior cells are from halo layers 2 & 3. The updates from halo layer 1 are all edge cells

**Pull request closed without merging**
